### ISSUE TITLE
Please publish the new version on npm

### ISSUE THREAD

**Issue by w8r** [kartena/Leaflet.Pancontrol#16]
The one with a new dependency. Actually, maybe the leaflet dependency can be removed altogether?

Thank you for the great work

**Comment by w8r** [comment]
I would re-publish it myself, but npm does not allow module removal anymore and it's bad manners altogether. Please, find a moment to do that

**Comment by pthorin** [comment]
Sorry for taking so long, I have published the new version to npm.

**Comment by w8r** [comment]
Thank you!
